# Projet Voltit

Voici l'export de Juin. Aidez-nous à comprendre l'activité du réseau et à identifier les points qui méritent notre attention.

données (qualité - data ingénierie) → question(s) → observation des données → hypothèses (données) → transformations (pandas) → contrôle le résultat → interprétation (datavisualisation)

In [2]:
import pandas as pd

pd.__version__

'3.0.6'

# Observation

## Quelques questions

- Quel semble être le rôle de chacun des 4 fichiers ?
- Quelles colonnes vous semblent importantes
- Quelles questions métiers pensez-vous déjà pouvoir poser avec ces données
  - Quelles stations ont le plus d'activité ?
  - Combien d'énergie est délivrée ?
  - Quelles sont les tranches horaires d'activités ?
  - Combien coûte la maintenance ?
  - Maintenance et l'activité sont liées ?
- Voyez-vous déjà des éléments qui nécessiteront une interprétation plutôt qu'un simple calcul ?
- C'est quoi l'activité de l'entreprise ?

In [3]:
stations = pd.read_csv("./data/stations.csv")
sessions = pd.read_csv("./data/sessions.csv")
maintenance = pd.read_csv("./data/maintenance.csv")
telemetry = pd.read_csv("./data/telemetry.csv")

In [4]:
stations.shape

(20, 7)

In [5]:
sessions.shape

(2318, 7)

In [6]:
stations.head(10)

,station_id,station_name,district,site_type,opened_on,connector_count,connector_max_power_kw
0,ST001,Voltit 01,Centre,residential,2026-06-01,2,22.0
1,ST002,Voltit 02,Sud,office,2026-06-01,6,11.0
2,ST003,Voltit 03,Centre,retail,2026-06-01,4,11.0
3,ST004,Voltit 04,Nord,residential,2026-06-01,3,22.0
4,ST005,Voltit 05,Est,residential,2026-06-01,6,11.0
5,ST006,Voltit 06,Ouest,retail,2026-06-01,2,22.0
6,ST007,Voltit 07,Nord,retail,2026-06-01,4,11.0
7,ST008,Voltit 08,Sud,office,2026-06-01,5,11.0
8,ST009,Voltit 09,Est,residential,2026-06-01,2,11.0
9,ST010,Voltit 10,Nord,retail,2026-06-01,6,22.0

In [7]:
stations.tail(10)

,station_id,station_name,district,site_type,opened_on,connector_count,connector_max_power_kw
10,ST011,Voltit 11,Est,retail,2026-06-01,5,7.4
11,ST012,Voltit 12,Sud,office,2026-06-01,5,22.0
12,ST013,Voltit 13,Ouest,office,2026-06-01,6,11.0
13,ST014,Voltit 14,Centre,office,2026-06-01,5,22.0
14,ST015,Voltit 15,Ouest,office,2026-06-01,4,11.0
15,ST016,Voltit 16,Ouest,residential,2026-06-01,6,11.0
16,ST017,Voltit 17,Sud,retail,2026-06-01,6,22.0
17,ST018,Voltit 18,Nord,office,2026-06-01,2,22.0
18,ST019,Voltit 19,Centre,residential,2026-06-01,3,7.4
19,ST020,Voltit 20,Est,residential,2026-06-16,2,22.0

In [8]:
sessions.tail(10)

,session_id,station_id,connector_no,started_at,ended_at,energy_kwh,status
2308,SE002309,ST017,1,2026-06-30 20:57:00,2026-06-30 22:45:00,16.382,completed
2309,SE002310,ST005,2,2026-06-30 21:16:00,NaN,2.919,ongoing
2310,SE002311,ST015,4,2026-06-30 22:12:00,NaN,1.617,ongoing
2311,SE002312,ST016,5,2026-06-30 22:20:00,NaN,4.203,ongoing
2312,SE002313,ST020,2,2026-06-30 22:20:00,NaN,23.786,ongoing
2313,SE002314,ST015,1,2026-06-30 22:48:00,NaN,6.239,ongoing
2314,SE002315,ST003,1,2026-06-30 23:00:00,NaN,5.442,ongoing
2315,SE002316,ST017,6,2026-06-30 23:20:00,NaN,7.124,ongoing
2316,SE002317,ST011,3,2026-06-30 23:32:00,NaN,0.763,ongoing
2317,SE002318,ST010,3,2026-06-30 23:41:00,NaN,3.002,ongoing

In [9]:
energy = sessions["energy_kwh"]
energy.median()

np.float64(11.6765)

In [10]:
subset = sessions[["station_id", "energy_kwh"]]
subset

     station_id  energy_kwh
0         ST003       2.026
1         ST002       5.706
2         ST008      21.035
3         ST018      57.397
4         ST011       9.153
...         ...         ...
2313      ST015       6.239
2314      ST003       5.442
2315      ST017       7.124
2316      ST011       0.763
2317      ST010       3.002

[2318 rows x 2 columns]

In [11]:
sessions.groupby("station_id")["energy_kwh"].mean().round(2)

station_id
ST002    20.63
ST003     6.25
ST004    47.63
ST005    23.32
ST006    11.06
ST007     6.03
ST008    18.18
ST009    25.52
ST010    12.69
ST011     3.64
ST012    40.39
ST013    18.69
ST014    38.35
ST015    18.40
ST016    23.12
ST017    12.28
ST018    34.90
ST019    15.24
ST020    41.45
Name: energy_kwh, dtype: float64

In [12]:
sessions.loc[
    sessions["energy_kwh"] == 0,
    ["station_id", "energy_kwh"]
]

     station_id  energy_kwh
11        ST008         0.0
34        ST011         0.0
72        ST007         0.0
83        ST002         0.0
95        ST002         0.0
...         ...         ...
2208      ST003         0.0
2210      ST004         0.0
2212      ST020         0.0
2230      ST011         0.0
2259      ST018         0.0

[97 rows x 2 columns]

In [13]:
sessions.describe().round(2)

       connector_no  energy_kwh
count       2318.00     2318.00
mean           2.92       18.02
std            1.57       18.62
min            1.00        0.00
25%            2.00        5.33
50%            3.00       11.68
75%            4.00       24.36
max            6.00      141.82

In [14]:
sessions.dtypes

session_id          str
station_id          str
connector_no      int64
started_at          str
ended_at            str
energy_kwh      float64
status              str
dtype: object

In [15]:
sessions.info()

<class 'pandas.DataFrame'>
RangeIndex: 2318 entries, 0 to 2317
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   session_id    2318 non-null   str
 1   station_id    2318 non-null   str
 2   connector_no  2318 non-null   int64
 3   started_at    2318 non-null   str
 4   ended_at      2304 non-null   str
 5   energy_kwh    2318 non-null   float64
 6   status        2318 non-null   str
dtypes: float64(1), int64(1), str(5)
memory usage: 126.9 KB

In [16]:
sessions.dtypes

session_id          str
station_id          str
connector_no      int64
started_at          str
ended_at            str
energy_kwh      float64
status              str
dtype: object

In [17]:
sessions.isna().sum()

session_id       0
station_id       0
connector_no     0
started_at       0
ended_at        14
energy_kwh       0
status           0
dtype: int64

In [18]:
telemetry.isna().sum()

station_id                0
observed_at               0
occupied_connectors     224
available_connectors      0
dtype: int64

In [19]:
maintenance.isna().sum()

maintenance_id      0
station_id          0
connector_no        0
started_at          0
ended_at            0
maintenance_type    0
cost_eur            9
dtype: int64

In [20]:
stations.isna().sum()

station_id                0
station_name              0
district                  0
site_type                 0
opened_on                 0
connector_count           0
connector_max_power_kw    0
dtype: int64

In [21]:
(sessions.isna().mean()*100).round(2)

session_id      0.0
station_id      0.0
connector_no    0.0
started_at      0.0
ended_at        0.6
energy_kwh      0.0
status          0.0
dtype: float64

**Exercice :** Traiter toutes les dates (de toutes les DataFrame)

- `maintenance.csv`
- `telemetry.csv`
- `stations.csv`

In [22]:
sessions["started_at"] = pd.to_datetime(sessions["started_at"])
sessions["ended_at"] = pd.to_datetime(sessions["ended_at"])

stations["opened_on"] = pd.to_datetime(stations["opened_on"])

telemetry["observed_at"] = pd.to_datetime(telemetry["observed_at"])

maintenance["ended_at"] = pd.to_datetime(maintenance["ended_at"])
maintenance["started_at"] = pd.to_datetime(maintenance["started_at"])

- Calcul
- Jointure
- Agregat

In [23]:
stations["station_id"].is_unique

True

In [24]:
telemetry["observed_at"].is_unique

False

In [25]:
telemetry.duplicated(
    subset=["station_id", "observed_at"]
).sum()

np.int64(0)

In [26]:

sessions["station_id"].nunique()

19

In [27]:
sessions["station_id"].duplicated().sum()

np.int64(2299)

In [28]:
sessions.duplicated().sum()

np.int64(0)

In [29]:
sessions[["station_id", "connector_no"]].drop_duplicates()

     station_id  connector_no
0         ST003             3
1         ST002             3
2         ST008             1
3         ST018             2
4         ST011             2
...         ...           ...
332       ST019             1
340       ST010             6
369       ST017             2
1224      ST020             1
1309      ST020             2

[82 rows x 2 columns]

In [30]:
sessions[sessions["energy_kwh"] == 0]

,session_id,station_id,connector_no,started_at,ended_at,energy_kwh,status
11,SE000012,ST008,4,2026-06-01 05:00:00,2026-06-01 05:02:00,0.0,failed
34,SE000035,ST011,4,2026-06-01 10:19:00,2026-06-01 10:25:00,0.0,failed
72,SE000073,ST007,2,2026-06-01 18:55:00,2026-06-01 18:58:00,0.0,failed
83,SE000084,ST002,2,2026-06-01 22:19:00,2026-06-01 22:25:00,0.0,failed
95,SE000096,ST002,5,2026-06-02 07:57:00,2026-06-02 08:01:00,0.0,failed
...,...,...,...,...,...,...,...
2208,SE002209,ST003,3,2026-06-29 17:02:00,2026-06-29 17:09:00,0.0,failed
2210,SE002211,ST004,3,2026-06-29 17:09:00,2026-06-29 17:16:00,0.0,failed
2212,SE002213,ST020,1,2026-06-29 17:30:00,2026-06-29 17:36:00,0.0,failed
2230,SE002231,ST011,2,2026-06-29 20:54:00,2026-06-29 21:01:00,0.0,failed
2259,SE002260,ST018,1,2026-06-30 09:29:00,2026-06-30 09:34:00,0.0,failed

In [31]:
maintenance["cost_eur"] = maintenance["cost_eur"].fillna(-1)

In [32]:
maintenance

,maintenance_id,station_id,connector_no,started_at,ended_at,maintenance_type,cost_eur
0,MA0001,ST004,2,2026-06-03 09:30:00,2026-06-03 10:00:00,corrective,-1.00
1,MA0002,ST013,4,2026-06-03 11:30:00,2026-06-03 13:00:00,preventive,333.41
2,MA0003,ST005,5,2026-06-05 09:00:00,2026-06-05 12:00:00,corrective,-1.00
3,MA0004,ST012,5,2026-06-05 10:00:00,2026-06-05 11:30:00,corrective,322.45
4,MA0005,ST006,1,2026-06-08 16:30:00,2026-06-08 17:30:00,preventive,612.98
5,MA0006,ST017,1,2026-06-09 11:30:00,2026-06-09 13:00:00,preventive,87.91
6,MA0007,ST014,3,2026-06-09 15:00:00,2026-06-09 16:00:00,preventive,403.78
7,MA0008,ST010,1,2026-06-12 07:30:00,2026-06-12 10:30:00,preventive,600.96
8,MA0009,ST016,2,2026-06-14 08:00:00,2026-06-14 11:00:00,corrective,140.60
9,MA0010,ST002,5,2026-06-14 11:30:00,2026-06-14 14:00:00,preventive,-1.00
10,MA0011,ST019,1,2026-06-14 12:30:00,2026-06-14 16:00:00,preventive,0.00
11,MA0012,ST003,4,2026-06-15 12:00:00,2026-06-15 14:30:00,preventive,517.02
12,MA0013,ST002,4,2026-06-16 13:00:00,2026-06-16 15:30:00,preventive,165.41
13,MA0014,ST004,2,2026-06-16 14:30:00,2026-06-16 15:30:00,corrective,-1.00
14,MA0015,ST006,2,2026-06-16 15:30:00,2026-06-16 19:00:00,corrective,192.12
15,MA0016,ST014,3,2026-06-17 13:00:00,2026-06-17 13:30:00,preventive,-1.00
16,MA0017,ST003,4,2026-06-17 15:30:00,2026-06-17 19:30:00,corrective,0.00
17,MA0018,ST006,1,2026-06-19 08:30:00,2026-06-19 09:30:00,corrective,-1.00
18,MA0019,ST017,3,2026-06-19 13:00:00,2026-06-19 13:30:00,corrective,256.65
19,MA0020,ST015,3,2026-06-19 16:30:00,2026-06-19 18:00:00,corrective,-1.00
20,MA0021,ST020,2,2026-06-20 12:00:00,2026-06-20 15:00:00,corrective,491.36
21,MA0022,ST002,2,2026-06-20 14:00:00,2026-06-20 15:00:00,preventive,487.28
22,MA0023,ST011,5,2026-06-21 07:30:00,2026-06-21 09:30:00,preventive,-1.00
23,MA0024,ST004,1,2026-06-21 16:00:00,2026-06-21 18:00:00,corrective,508.56
24,MA0025,ST019,2,2026-06-22 07:30:00,2026-06-22 08:00:00,preventive,245.05
25,MA0026,ST018,2,2026-06-22 12:30:00,2026-06-22 13:00:00,preventive,202.91
26,MA0027,ST005,3,2026-06-23 09:00:00,2026-06-23 12:00:00,preventive,0.00
27,MA0028,ST010,5,2026-06-25 10:00:00,2026-06-25 13:30:00,corrective,605.23
28,MA0029,ST014,1,2026-06-26 10:00:00,2026-06-26 10:30:00,corrective,-1.00
29,MA0030,ST003,4,2026-06-26 13:00:00,2026-06-26 15:30:00,preventive,542.78
30,MA0031,ST013,4,2026-06-28 11:00:00,2026-06-28 14:00:00,corrective,363.63
31,MA0032,ST010,4,2026-06-30 14:00:00,2026-06-30 15:30:00,corrective,271.76

In [33]:
telemetry[telemetry["occupied_connectors"].isna()]

,station_id,observed_at,occupied_connectors,available_connectors
1934,ST002,2026-06-11 07:00:00,NaN,6
2046,ST002,2026-06-13 15:00:00,NaN,6
2190,ST002,2026-06-16 15:00:00,NaN,5
2329,ST002,2026-06-19 12:30:00,NaN,6
2362,ST002,2026-06-20 05:00:00,NaN,6
...,...,...,...,...
27211,ST019,2026-06-27 23:30:00,NaN,3
27490,ST020,2026-06-18 19:00:00,NaN,2
27565,ST020,2026-06-20 08:30:00,NaN,2
27934,ST020,2026-06-28 01:00:00,NaN,2
28020,ST020,2026-06-29 20:00:00,NaN,2

In [34]:
has_session = stations["station_id"].isin(sessions["station_id"])
has_session

0     False
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
Name: station_id, dtype: bool

In [35]:
stations[~has_session]

,station_id,station_name,district,site_type,opened_on,connector_count,connector_max_power_kw
0,ST001,Voltit 01,Centre,residential,2026-06-01,2,22.0

In [36]:
sessions["energy_kwh"] ** 2

0          4.104676
1         32.558436
2        442.471225
3       3294.415609
4         83.777409
           ...
2313      38.925121
2314      29.615364
2315      50.751376
2316       0.582169
2317       9.012004
Name: energy_kwh, Length: 2318, dtype: float64

# !todo : Générer les lignes absentes de télémétrie

## Calcul

In [37]:
sessions["energy_kwh"].mean().round(2)

np.float64(18.02)

In [38]:
sessions.loc[
    sessions["energy_kwh"] > 0,
    "energy_kwh"
].mean().round(2)

np.float64(18.8)

`Quelle(s) ligne(s) appartiennent réellement à la population que je veux analyser ?`

### Calculs dérivés

In [39]:
sessions["duration"] = sessions["ended_at"] - sessions["started_at"]
sessions

,session_id,station_id,connector_no,started_at,ended_at,energy_kwh,status,duration
0,SE000001,ST003,3,2026-06-01 00:26:00,2026-06-01 00:51:00,2.026,completed,0 days 00:25:00
1,SE000002,ST002,3,2026-06-01 00:34:00,2026-06-01 03:34:00,5.706,completed,0 days 03:00:00
2,SE000003,ST008,1,2026-06-01 00:34:00,2026-06-01 04:26:00,21.035,completed,0 days 03:52:00
3,SE000004,ST018,2,2026-06-01 01:46:00,2026-06-01 09:46:00,57.397,completed,0 days 08:00:00
4,SE000005,ST011,2,2026-06-01 01:52:00,2026-06-01 04:19:00,9.153,completed,0 days 02:27:00
...,...,...,...,...,...,...,...,...
2313,SE002314,ST015,1,2026-06-30 22:48:00,NaT,6.239,ongoing,NaT
2314,SE002315,ST003,1,2026-06-30 23:00:00,NaT,5.442,ongoing,NaT
2315,SE002316,ST017,6,2026-06-30 23:20:00,NaT,7.124,ongoing,NaT
2316,SE002317,ST011,3,2026-06-30 23:32:00,NaT,0.763,ongoing,NaT
2317,SE002318,ST010,3,2026-06-30 23:41:00,NaT,3.002,ongoing,NaT

In [40]:
sessions["duration_hours"] = (
    sessions["duration"].dt.total_seconds() / 3600
)
sessions

,session_id,station_id,connector_no,started_at,ended_at,energy_kwh,status,duration,duration_hours
0,SE000001,ST003,3,2026-06-01 00:26:00,2026-06-01 00:51:00,2.026,completed,0 days 00:25:00,0.416667
1,SE000002,ST002,3,2026-06-01 00:34:00,2026-06-01 03:34:00,5.706,completed,0 days 03:00:00,3.000000
2,SE000003,ST008,1,2026-06-01 00:34:00,2026-06-01 04:26:00,21.035,completed,0 days 03:52:00,3.866667
3,SE000004,ST018,2,2026-06-01 01:46:00,2026-06-01 09:46:00,57.397,completed,0 days 08:00:00,8.000000
4,SE000005,ST011,2,2026-06-01 01:52:00,2026-06-01 04:19:00,9.153,completed,0 days 02:27:00,2.450000
...,...,...,...,...,...,...,...,...,...
2313,SE002314,ST015,1,2026-06-30 22:48:00,NaT,6.239,ongoing,NaT,NaN
2314,SE002315,ST003,1,2026-06-30 23:00:00,NaT,5.442,ongoing,NaT,NaN
2315,SE002316,ST017,6,2026-06-30 23:20:00,NaT,7.124,ongoing,NaT,NaN
2316,SE002317,ST011,3,2026-06-30 23:32:00,NaT,0.763,ongoing,NaT,NaN
2317,SE002318,ST010,3,2026-06-30 23:41:00,NaT,3.002,ongoing,NaT,NaN

In [41]:
sessions[sessions["started_at"].dt.day_of_week >= 5]

,session_id,station_id,connector_no,started_at,ended_at,energy_kwh,status,duration,duration_hours
402,SE000403,ST010,6,2026-06-06 01:10:00,2026-06-06 03:29:00,21.804,completed,0 days 02:19:00,2.316667
403,SE000404,ST017,2,2026-06-06 01:34:00,2026-06-06 02:45:00,14.906,completed,0 days 01:11:00,1.183333
404,SE000405,ST010,5,2026-06-06 01:59:00,2026-06-06 04:10:00,21.771,completed,0 days 02:11:00,2.183333
405,SE000406,ST010,2,2026-06-06 02:17:00,2026-06-06 03:12:00,5.136,completed,0 days 00:55:00,0.916667
406,SE000407,ST005,6,2026-06-06 03:19:00,2026-06-06 03:26:00,0.000,failed,0 days 00:07:00,0.116667
...,...,...,...,...,...,...,...,...,...
2140,SE002141,ST016,5,2026-06-28 20:45:00,2026-06-29 00:42:00,13.578,completed,0 days 03:57:00,3.950000
2141,SE002142,ST004,2,2026-06-28 21:18:00,2026-06-29 06:32:00,26.222,completed,0 days 09:14:00,9.233333
2142,SE002143,ST004,3,2026-06-28 21:34:00,2026-06-29 00:30:00,25.544,completed,0 days 02:56:00,2.933333
2143,SE002144,ST016,2,2026-06-28 23:25:00,2026-06-29 02:03:00,19.772,completed,0 days 02:38:00,2.633333
2144,SE002145,ST005,1,2026-06-28 23:39:00,2026-06-29 04:02:00,19.878,completed,0 days 04:23:00,4.383333

In [42]:
sessions[
    (sessions["status"] == "completed")
        &
    (sessions["energy_kwh"] > 0)
]
sessions

,session_id,station_id,connector_no,started_at,ended_at,energy_kwh,status,duration,duration_hours
0,SE000001,ST003,3,2026-06-01 00:26:00,2026-06-01 00:51:00,2.026,completed,0 days 00:25:00,0.416667
1,SE000002,ST002,3,2026-06-01 00:34:00,2026-06-01 03:34:00,5.706,completed,0 days 03:00:00,3.000000
2,SE000003,ST008,1,2026-06-01 00:34:00,2026-06-01 04:26:00,21.035,completed,0 days 03:52:00,3.866667
3,SE000004,ST018,2,2026-06-01 01:46:00,2026-06-01 09:46:00,57.397,completed,0 days 08:00:00,8.000000
4,SE000005,ST011,2,2026-06-01 01:52:00,2026-06-01 04:19:00,9.153,completed,0 days 02:27:00,2.450000
...,...,...,...,...,...,...,...,...,...
2313,SE002314,ST015,1,2026-06-30 22:48:00,NaT,6.239,ongoing,NaT,NaN
2314,SE002315,ST003,1,2026-06-30 23:00:00,NaT,5.442,ongoing,NaT,NaN
2315,SE002316,ST017,6,2026-06-30 23:20:00,NaT,7.124,ongoing,NaT,NaN
2316,SE002317,ST011,3,2026-06-30 23:32:00,NaT,0.763,ongoing,NaT,NaN
2317,SE002318,ST010,3,2026-06-30 23:41:00,NaT,3.002,ongoing,NaT,NaN

# Agreger

In [45]:
sessions_per_station = sessions.groupby("station_id")
sessions_per_station.size()

station_id
ST002    131
ST003    122
ST004     52
ST005    174
ST006     59
ST007    180
ST008    132
ST009     61
ST010    199
ST011    177
ST012     93
ST013    162
ST014     82
ST015     98
ST016    179
ST017    270
ST018     47
ST019     79
ST020     21
dtype: int64

In [46]:
sessions_per_station = (
    sessions.groupby("station_id")
    .size()
    .sort_values(ascending=False)
)
sessions_per_station

station_id
ST017    270
ST010    199
ST007    180
ST016    179
ST011    177
ST005    174
ST013    162
ST008    132
ST002    131
ST003    122
ST015     98
ST012     93
ST014     82
ST019     79
ST009     61
ST006     59
ST004     52
ST018     47
ST020     21
dtype: int64

In [47]:
sessions.groupby("station_id")["ended_at"].count()

station_id
ST002    131
ST003    121
ST004     52
ST005    173
ST006     59
ST007    180
ST008    131
ST009     60
ST010    198
ST011    176
ST012     93
ST013    162
ST014     82
ST015     96
ST016    176
ST017    269
ST018     47
ST019     79
ST020     19
Name: ended_at, dtype: int64

In [51]:
completed = sessions[sessions["status"] == "completed"].copy()

In [56]:
station_summary = (
    completed.groupby("station_id", as_index=True)
        .agg(
            session_count=("session_id", "size"),
            total_energy_kwh=("energy_kwh", "sum"),
            mean_energy_kwh=("energy_kwh", "mean"),
        )
).sort_values("total_energy_kwh", ascending=False).round(2)
station_summary

            session_count  total_energy_kwh  mean_energy_kwh
station_id
ST016                 166           4087.56            24.62
ST005                 160           4054.85            25.34
ST012                  92           3756.35            40.83
ST017                 257           3308.69            12.87
ST014                  80           3144.30            39.30
ST013                 158           3027.13            19.16
ST002                 123           2702.36            21.97
ST010                 194           2521.53            13.00
ST004                  49           2477.00            50.55
ST008                 124           2377.89            19.18
ST015                  92           1795.25            19.51
ST018                  44           1640.38            37.28
ST009                  60           1530.58            25.51
ST019                  72           1204.26            16.73
ST007                 175           1085.16             6.20
ST020                  18            797.24            44.29
ST003                 117            756.93             6.47
ST006                  58            652.39            11.25
ST011                 168            643.69             3.83

session N - 1 station